version: '3.8'
services:
  service:
    container_name: server
    build:
      context: server
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
    healthcheck:
      test: "exit 0"
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0.12
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "examplepassword"
#    volumes: #
#      - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"
