version: '3.8'

services:
  mongodb:
    image: mongo:6.0.12
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    ports:
      - "27017:27017"
    # volumes:
    #   - mongodb_data:/data/db

volumes:
  mongodb_data:
